### ISSUE TITLE
Socket is already bound

### ISSUE THREAD

**Issue by cjimti** [gildean/node-udp-proxy#3]
when running testIPv4.js and ./testIPv6.js I get:

 ```
$ node ./testIPv6.js 
5 Sep 17:10:23 -  * IPv4 to IPv4  proxy * | by : | ok:2012
5 Sep 17:10:23 -               running on | os : | darwin
5 Sep 17:10:23 -    proxy-server ready on | IPv4 | 127.0.0.1:5353
5 Sep 17:10:23 -  traffic is forwarded to | IPv4 | 8.8.8.8:53
5 Sep 17:10:23 -            mitm ready on | IPv4 | 0.0.0.0:5354
5 Sep 17:10:23 -         mitmmessage from | IPv4 | 127.0.0.1:56727
5 Sep 17:10:23 -    mitmproxy is bound to | IPv4 | 127.0.0.1:49928
5 Sep 17:10:23 -     mitmpeer is bound to | IPv4 | 127.0.0.1:56727

dgram.js:163
    throw new Error('Socket is already bound');
          ^
Error: Socket is already bound
    at Socket.bind (dgram.js:163:11)
    at Socket.<anonymous> (/workspace/node/proxy/node_modules/udp-proxy/index.js:101:21)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:437:8)
 ```

 ```
$ node -v
v0.10.17
 ```

**Comment by gildean** [comment]
This should now be fixed in version 1.x.x forwards (released on npm).
